

-- creating silver tables --------------------------------- -----------

CREATE OR REPLACE TABLE SILVER_CUSTOMERS (
    CUSTOMER_SK     NUMBER AUTOINCREMENT,
    CUSTOMER_ID     VARCHAR(20),
    CUSTOMER_NAME   VARCHAR(100),
    CUSTOMER_EMAIL  VARCHAR(150),
    CUSTOMER_PHONE  VARCHAR(20),
    CUSTOMER_CITY   VARCHAR(50),
    CUSTOMER_STATE  VARCHAR(50),

    VALID_FROM      TIMESTAMP_NTZ,
    VALID_TO        TIMESTAMP_NTZ,
    IS_CURRENT      VARCHAR(1)
);

CREATE OR REPLACE TABLE SILVER_PRODUCTS (
    PRODUCT_ID           VARCHAR(20),
    PRODUCT_NAME         VARCHAR(100),
    PRODUCT_CATEGORY     VARCHAR(50),
    PRODUCT_DESCRIPTION  VARCHAR(255),
    DESCRIPTION_DETAILS  VARCHAR(255)
);

CREATE OR REPLACE TABLE SILVER_STORES (
    STORE_ID      VARCHAR(20),
    STORE_CITY    VARCHAR(50),
    STORE_STATE   VARCHAR(50),
    STORE_REGION  VARCHAR(50),
    REGION_HEAD   VARCHAR(100)
);

CREATE OR REPLACE TABLE SILVER_PAYMENT_TYPE (
    PAYMENT_TYPE  VARCHAR(20),
    IS_DIGITAL    VARCHAR(1)
);

CREATE OR REPLACE TABLE SILVER_ORDERS (
    ORDER_ID           VARCHAR(20),
    ORDER_TIMESTAMP    TIMESTAMP_NTZ,
    ORDER_STATUS       VARCHAR(20),
    CUSTOMER_ID        VARCHAR(20),
    PRODUCT_ID         VARCHAR(20),
    STORE_ID           VARCHAR(20),

    QUANTITY           NUMBER(10,0),
    UNIT_PRICE         NUMBER(12,2),
    DISCOUNT_AMOUNT    NUMBER(12,2),

    PAYMENT_TYPE       VARCHAR(20),
    ORDER_AMOUNT       NUMBER(14,2),

    RECORD_UPDATED_AT  TIMESTAMP_NTZ
);

----- Inserting the values into the silver table ---------------------------

INSERT INTO SILVER_PAYMENT_TYPE
SELECT
    PAYMENT_TYPE,
    IS_DIGITAL
FROM PAYMENT_TYPE_LOOK_UP;
--truncate table silver_payment_type;
select * from silver_payment_type;

MERGE INTO SILVER_PRODUCTS tgt
USING (
    SELECT DISTINCT
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_CATEGORY,
        NULL AS PRODUCT_DESCRIPTION,
        NULL AS DESCRIPTION_DETAILS
    FROM RETAIL
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID

WHEN MATCHED THEN
    UPDATE SET
        PRODUCT_NAME        = src.PRODUCT_NAME,
        PRODUCT_CATEGORY    = src.PRODUCT_CATEGORY,
        PRODUCT_DESCRIPTION = src.PRODUCT_DESCRIPTION,
        DESCRIPTION_DETAILS = src.DESCRIPTION_DETAILS

WHEN NOT MATCHED THEN
    INSERT (
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_CATEGORY,
        PRODUCT_DESCRIPTION,
        DESCRIPTION_DETAILS
    )
    VALUES (
        src.PRODUCT_ID,
        src.PRODUCT_NAME,
        src.PRODUCT_CATEGORY,
        src.PRODUCT_DESCRIPTION,
        src.DESCRIPTION_DETAILS
    );


MERGE INTO SILVER_STORES tgt
USING (
    SELECT DISTINCT
        ro.STORE_ID,
        ro.STORE_CITY,
        ro.STORE_STATE,
        ro.STORE_REGION,
        sr.REGION_HEAD
    FROM RETAIL ro
    LEFT JOIN STORE_REGION_LOOKUP sr
        ON ro.STORE_REGION = sr.STORE_REGION
) src
ON tgt.STORE_ID = src.STORE_ID

WHEN MATCHED THEN
    UPDATE SET
        STORE_CITY   = src.STORE_CITY,
        STORE_STATE  = src.STORE_STATE,
        STORE_REGION = src.STORE_REGION,
        REGION_HEAD  = src.REGION_HEAD

WHEN NOT MATCHED THEN
    INSERT (
        STORE_ID,
        STORE_CITY,
        STORE_STATE,
        STORE_REGION,
        REGION_HEAD
    )
    VALUES (
        src.STORE_ID,
        src.STORE_CITY,
        src.STORE_STATE,
        src.STORE_REGION,
        src.REGION_HEAD
    );



  INSERT INTO SILVER_CUSTOMERS (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_EMAIL,
    CUSTOMER_PHONE,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
)
SELECT DISTINCT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_EMAIL,
    CUSTOMER_PHONE,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    RECORD_UPDATED_AT,
    '9999-12-31',
    'Y'
FROM RETAIL ro
WHERE NOT EXISTS (
    SELECT 1
    FROM SILVER_CUSTOMERS sc
    WHERE sc.CUSTOMER_ID = ro.CUSTOMER_ID
      AND sc.IS_CURRENT = 'Y'
      AND sc.CUSTOMER_EMAIL = ro.CUSTOMER_EMAIL
      AND sc.CUSTOMER_PHONE = ro.CUSTOMER_PHONE
      AND sc.CUSTOMER_CITY  = ro.CUSTOMER_CITY
);

MERGE INTO SILVER_ORDERS tgt
USING (
    SELECT
        ORDER_ID,
        ORDER_TIMESTAMP,
        ORDER_STATUS,
        CUSTOMER_ID,
        PRODUCT_ID,
        STORE_ID,
        QUANTITY,
        UNIT_PRICE,
        DISCOUNT_AMOUNT,
        PAYMENT_TYPE,
        (QUANTITY * UNIT_PRICE) - DISCOUNT_AMOUNT AS ORDER_AMOUNT,
        RECORD_UPDATED_AT
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY ORDER_ID
                   ORDER BY RECORD_UPDATED_AT DESC
               ) AS RN
        FROM RETAIL
    )
    WHERE RN = 1
) src
ON tgt.ORDER_ID = src.ORDER_ID

WHEN MATCHED THEN
    UPDATE SET
        ORDER_STATUS      = src.ORDER_STATUS,
        ORDER_AMOUNT      = src.ORDER_AMOUNT,
        RECORD_UPDATED_AT = src.RECORD_UPDATED_AT

WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID,
        ORDER_TIMESTAMP,
        ORDER_STATUS,
        CUSTOMER_ID,
        PRODUCT_ID,
        STORE_ID,
        QUANTITY,
        UNIT_PRICE,
        DISCOUNT_AMOUNT,
        PAYMENT_TYPE,
        ORDER_AMOUNT,
        RECORD_UPDATED_AT
    )
    VALUES (
        src.ORDER_ID,
        src.ORDER_TIMESTAMP,
        src.ORDER_STATUS,
        src.CUSTOMER_ID,
        src.PRODUCT_ID,
        src.STORE_ID,
        src.QUANTITY,
        src.UNIT_PRICE,
        src.DISCOUNT_AMOUNT,
        src.PAYMENT_TYPE,
        src.ORDER_AMOUNT,
        src.RECORD_UPDATED_AT
    );

    